name: "fused_bert"
op: "Bert"
input: "bert/encoder/Reshape_1"
input: "bert/encoder/Reshape"
input: "bert/encoder/layer_0/attention/self/query/kernel/read"
input: "bert/encoder/layer_0/attention/self/query/bias/read"
input: "bert/encoder/layer_0/attention/self/key/kernel/read"
input: "bert/encoder/layer_0/attention/self/key/bias/read"
input: "bert/encoder/layer_0/attention/self/value/kernel/read"
input: "bert/encoder/layer_0/attention/self/value/bias/read"
input: "bert/encoder/layer_0/attention/output/dense/kernel/read"
input: "bert/encoder/layer_0/attention/output/dense/bias/read"
input: "bert/encoder/layer_0/attention/output/layer_normalization_1/mul_2/ReadVariableOp"
input: "bert/encoder/layer_0/attention/output/layer_normalization_1/add/ReadVariableOp"
input: "bert/encoder/layer_0/intermediate/dense/kernel/read"
input: "bert/encoder/layer_0/intermediate/dense/bias/read"
input: "bert/encoder/layer_0/output/dense/kernel/read"
input: "bert/encoder/layer_0/output/dense/bias/read"
input: "bert/encoder/layer_0/output/layer_normalization_2/mul_2/ReadVariableOp"
input: "bert/encoder/layer_0/output/layer_normalization_2/add/ReadVariableOp"
input: "bert/encoder/layer_1/attention/self/query/kernel/read"
input: "bert/encoder/layer_1/attention/self/query/bias/read"
input: "bert/encoder/layer_1/attention/self/key/kernel/read"
input: "bert/encoder/layer_1/attention/self/key/bias/read"
input: "bert/encoder/layer_1/attention/self/value/kernel/read"
input: "bert/encoder/layer_1/attention/self/value/bias/read"
input: "bert/encoder/layer_1/attention/output/dense/kernel/read"
input: "bert/encoder/layer_1/attention/output/dense/bias/read"
input: "bert/encoder/layer_1/attention/output/layer_normalization_3/mul_2/ReadVariableOp"
input: "bert/encoder/layer_1/attention/output/layer_normalization_3/add/ReadVariableOp"
input: "bert/encoder/layer_1/intermediate/dense/kernel/read"
input: "bert/encoder/layer_1/intermediate/dense/bias/read"
input: "bert/encoder/layer_1/output/dense/kernel/read"
input: "bert/encoder/layer_1/output/dense/bias/read"
input: "bert/encoder/layer_1/output/layer_normalization_4/mul_2/ReadVariableOp"
input: "bert/encoder/layer_1/output/layer_normalization_4/add/ReadVariableOp"
input: "bert/encoder/layer_2/attention/self/query/kernel/read"
input: "bert/encoder/layer_2/attention/self/query/bias/read"
input: "bert/encoder/layer_2/attention/self/key/kernel/read"
input: "bert/encoder/layer_2/attention/self/key/bias/read"
input: "bert/encoder/layer_2/attention/self/value/kernel/read"
input: "bert/encoder/layer_2/attention/self/value/bias/read"
input: "bert/encoder/layer_2/attention/output/dense/kernel/read"
input: "bert/encoder/layer_2/attention/output/dense/bias/read"
input: "bert/encoder/layer_2/attention/output/layer_normalization_5/mul_2/ReadVariableOp"
input: "bert/encoder/layer_2/attention/output/layer_normalization_5/add/ReadVariableOp"
input: "bert/encoder/layer_2/intermediate/dense/kernel/read"
input: "bert/encoder/layer_2/intermediate/dense/bias/read"
input: "bert/encoder/layer_2/output/dense/kernel/read"
input: "bert/encoder/layer_2/output/dense/bias/read"
input: "bert/encoder/layer_2/output/layer_normalization_6/mul_2/ReadVariableOp"
input: "bert/encoder/layer_2/output/layer_normalization_6/add/ReadVariableOp"
input: "bert/encoder/layer_3/attention/self/query/kernel/read"
input: "bert/encoder/layer_3/attention/self/query/bias/read"
input: "bert/encoder/layer_3/attention/self/key/kernel/read"
input: "bert/encoder/layer_3/attention/self/key/bias/read"
input: "bert/encoder/layer_3/attention/self/value/kernel/read"
input: "bert/encoder/layer_3/attention/self/value/bias/read"
input: "bert/encoder/layer_3/attention/output/dense/kernel/read"
input: "bert/encoder/layer_3/attention/output/dense/bias/read"
input: "bert/encoder/layer_3/attention/output/layer_normalization_7/mul_2/ReadVariableOp"
input: "bert/encoder/layer_3/attention/output/layer_normalization_7/add/ReadVariableOp"
input: "bert/encoder/layer_3/intermediate/dense/kernel/read"
input: "bert/encoder/layer_3/intermediate/dense/bias/read"
input: "bert/encoder/layer_3/output/dense/kernel/read"
input: "bert/encoder/layer_3/output/dense/bias/read"
input: "bert/encoder/layer_3/output/layer_normalization_8/mul_2/ReadVariableOp"
input: "bert/encoder/layer_3/output/layer_normalization_8/add/ReadVariableOp"
input: "bert/encoder/layer_4/attention/self/query/kernel/read"
input: "bert/encoder/layer_4/attention/self/query/bias/read"
input: "bert/encoder/layer_4/attention/self/key/kernel/read"
input: "bert/encoder/layer_4/attention/self/key/bias/read"
input: "bert/encoder/layer_4/attention/self/value/kernel/read"
input: "bert/encoder/layer_4/attention/self/value/bias/read"
input: "bert/encoder/layer_4/attention/output/dense/kernel/read"
input: "bert/encoder/layer_4/attention/output/dense/bias/read"
input: "bert/encoder/layer_4/attention/output/layer_normalization_9/mul_2/ReadVariableOp"
input: "bert/encoder/layer_4/attention/output/layer_normalization_9/add/ReadVariableOp"
input: "bert/encoder/layer_4/intermediate/dense/kernel/read"
input: "bert/encoder/layer_4/intermediate/dense/bias/read"
input: "bert/encoder/layer_4/output/dense/kernel/read"
input: "bert/encoder/layer_4/output/dense/bias/read"
input: "bert/encoder/layer_4/output/layer_normalization_10/mul_2/ReadVariableOp"
input: "bert/encoder/layer_4/output/layer_normalization_10/add/ReadVariableOp"
input: "bert/encoder/layer_5/attention/self/query/kernel/read"
input: "bert/encoder/layer_5/attention/self/query/bias/read"
input: "bert/encoder/layer_5/attention/self/key/kernel/read"
input: "bert/encoder/layer_5/attention/self/key/bias/read"
input: "bert/encoder/layer_5/attention/self/value/kernel/read"
input: "bert/encoder/layer_5/attention/self/value/bias/read"
input: "bert/encoder/layer_5/attention/output/dense/kernel/read"
input: "bert/encoder/layer_5/attention/output/dense/bias/read"
input: "bert/encoder/layer_5/attention/output/layer_normalization_11/mul_2/ReadVariableOp"
input: "bert/encoder/layer_5/attention/output/layer_normalization_11/add/ReadVariableOp"
input: "bert/encoder/layer_5/intermediate/dense/kernel/read"
input: "bert/encoder/layer_5/intermediate/dense/bias/read"
input: "bert/encoder/layer_5/output/dense/kernel/read"
input: "bert/encoder/layer_5/output/dense/bias/read"
input: "bert/encoder/layer_5/output/layer_normalization_12/mul_2/ReadVariableOp"
input: "bert/encoder/layer_5/output/layer_normalization_12/add/ReadVariableOp"
input: "bert/encoder/layer_6/attention/self/query/kernel/read"
input: "bert/encoder/layer_6/attention/self/query/bias/read"
input: "bert/encoder/layer_6/attention/self/key/kernel/read"
input: "bert/encoder/layer_6/attention/self/key/bias/read"
input: "bert/encoder/layer_6/attention/self/value/kernel/read"
input: "bert/encoder/layer_6/attention/self/value/bias/read"
input: "bert/encoder/layer_6/attention/output/dense/kernel/read"
input: "bert/encoder/layer_6/attention/output/dense/bias/read"
input: "bert/encoder/layer_6/attention/output/layer_normalization_13/mul_2/ReadVariableOp"
input: "bert/encoder/layer_6/attention/output/layer_normalization_13/add/ReadVariableOp"
input: "bert/encoder/layer_6/intermediate/dense/kernel/read"
input: "bert/encoder/layer_6/intermediate/dense/bias/read"
input: "bert/encoder/layer_6/output/dense/kernel/read"
input: "bert/encoder/layer_6/output/dense/bias/read"
input: "bert/encoder/layer_6/output/layer_normalization_14/mul_2/ReadVariableOp"
input: "bert/encoder/layer_6/output/layer_normalization_14/add/ReadVariableOp"
input: "bert/encoder/layer_7/attention/self/query/kernel/read"
input: "bert/encoder/layer_7/attention/self/query/bias/read"
input: "bert/encoder/layer_7/attention/self/key/kernel/read"
input: "bert/encoder/layer_7/attention/self/key/bias/read"
input: "bert/encoder/layer_7/attention/self/value/kernel/read"
input: "bert/encoder/layer_7/attention/self/value/bias/read"
input: "bert/encoder/layer_7/attention/output/dense/kernel/read"
input: "bert/encoder/layer_7/attention/output/dense/bias/read"
input: "bert/encoder/layer_7/attention/output/layer_normalization_15/mul_2/ReadVariableOp"
input: "bert/encoder/layer_7/attention/output/layer_normalization_15/add/ReadVariableOp"
input: "bert/encoder/layer_7/intermediate/dense/kernel/read"
input: "bert/encoder/layer_7/intermediate/dense/bias/read"
input: "bert/encoder/layer_7/output/dense/kernel/read"
input: "bert/encoder/layer_7/output/dense/bias/read"
input: "bert/encoder/layer_7/output/layer_normalization_16/mul_2/ReadVariableOp"
input: "bert/encoder/layer_7/output/layer_normalization_16/add/ReadVariableOp"
input: "bert/encoder/layer_8/attention/self/query/kernel/read"
input: "bert/encoder/layer_8/attention/self/query/bias/read"
input: "bert/encoder/layer_8/attention/self/key/kernel/read"
input: "bert/encoder/layer_8/attention/self/key/bias/read"
input: "bert/encoder/layer_8/attention/self/value/kernel/read"
input: "bert/encoder/layer_8/attention/self/value/bias/read"
input: "bert/encoder/layer_8/attention/output/dense/kernel/read"
input: "bert/encoder/layer_8/attention/output/dense/bias/read"
input: "bert/encoder/layer_8/attention/output/layer_normalization_17/mul_2/ReadVariableOp"
input: "bert/encoder/layer_8/attention/output/layer_normalization_17/add/ReadVariableOp"
input: "bert/encoder/layer_8/intermediate/dense/kernel/read"
input: "bert/encoder/layer_8/intermediate/dense/bias/read"
input: "bert/encoder/layer_8/output/dense/kernel/read"
input: "bert/encoder/layer_8/output/dense/bias/read"
input: "bert/encoder/layer_8/output/layer_normalization_18/mul_2/ReadVariableOp"
input: "bert/encoder/layer_8/output/layer_normalization_18/add/ReadVariableOp"
input: "bert/encoder/layer_9/attention/self/query/kernel/read"
input: "bert/encoder/layer_9/attention/self/query/bias/read"
input: "bert/encoder/layer_9/attention/self/key/kernel/read"
input: "bert/encoder/layer_9/attention/self/key/bias/read"
input: "bert/encoder/layer_9/attention/self/value/kernel/read"
input: "bert/encoder/layer_9/attention/self/value/bias/read"
input: "bert/encoder/layer_9/attention/output/dense/kernel/read"
input: "bert/encoder/layer_9/attention/output/dense/bias/read"
input: "bert/encoder/layer_9/attention/output/layer_normalization_19/mul_2/ReadVariableOp"
input: "bert/encoder/layer_9/attention/output/layer_normalization_19/add/ReadVariableOp"
input: "bert/encoder/layer_9/intermediate/dense/kernel/read"
input: "bert/encoder/layer_9/intermediate/dense/bias/read"
input: "bert/encoder/layer_9/output/dense/kernel/read"
input: "bert/encoder/layer_9/output/dense/bias/read"
input: "bert/encoder/layer_9/output/layer_normalization_20/mul_2/ReadVariableOp"
input: "bert/encoder/layer_9/output/layer_normalization_20/add/ReadVariableOp"
input: "bert/encoder/layer_10/attention/self/query/kernel/read"
input: "bert/encoder/layer_10/attention/self/query/bias/read"
input: "bert/encoder/layer_10/attention/self/key/kernel/read"
input: "bert/encoder/layer_10/attention/self/key/bias/read"
input: "bert/encoder/layer_10/attention/self/value/kernel/read"
input: "bert/encoder/layer_10/attention/self/value/bias/read"
input: "bert/encoder/layer_10/attention/output/dense/kernel/read"
input: "bert/encoder/layer_10/attention/output/dense/bias/read"
input: "bert/encoder/layer_10/attention/output/layer_normalization_21/mul_2/ReadVariableOp"
input: "bert/encoder/layer_10/attention/output/layer_normalization_21/add/ReadVariableOp"
input: "bert/encoder/layer_10/intermediate/dense/kernel/read"
input: "bert/encoder/layer_10/intermediate/dense/bias/read"
input: "bert/encoder/layer_10/output/dense/kernel/read"
input: "bert/encoder/layer_10/output/dense/bias/read"
input: "bert/encoder/layer_10/output/layer_normalization_22/mul_2/ReadVariableOp"
input: "bert/encoder/layer_10/output/layer_normalization_22/add/ReadVariableOp"
input: "bert/encoder/layer_11/attention/self/query/kernel/read"
input: "bert/encoder/layer_11/attention/self/query/bias/read"
input: "bert/encoder/layer_11/attention/self/key/kernel/read"
input: "bert/encoder/layer_11/attention/self/key/bias/read"
input: "bert/encoder/layer_11/attention/self/value/kernel/read"
input: "bert/encoder/layer_11/attention/self/value/bias/read"
input: "bert/encoder/layer_11/attention/output/dense/kernel/read"
input: "bert/encoder/layer_11/attention/output/dense/bias/read"
input: "bert/encoder/layer_11/attention/output/layer_normalization_23/mul_2/ReadVariableOp"
input: "bert/encoder/layer_11/attention/output/layer_normalization_23/add/ReadVariableOp"
input: "bert/encoder/layer_11/intermediate/dense/kernel/read"
input: "bert/encoder/layer_11/intermediate/dense/bias/read"
input: "bert/encoder/layer_11/output/dense/kernel/read"
input: "bert/encoder/layer_11/output/dense/bias/read"
input: "bert/encoder/layer_11/output/layer_normalization_24/mul_2/ReadVariableOp"
input: "bert/encoder/layer_11/output/layer_normalization_24/add/ReadVariableOp"
attr {
  key: "HiddenAct"
  value {
    s: "gelu_tanh"
  }
}
attr {
  key: "HiddenSize"
  value {
    i: 768
  }
}
attr {
  key: "IntermediateSize"
  value {
    i: 3072
  }
}
attr {
  key: "MaskT"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "NumAttentionHeads"
  value {
    i: 12
  }
}
attr {
  key: "NumWeights"
  value {
    i: 192
  }
}
attr {
  key: "_output_shapes"
  value {
    list {
      shape {
        unknown_rank: true
      }
    }
  }
}
