name: "fused_bert"
op: "Bert"
input: "model/bert_encoder/dropout/Identity"
input: "model/bert_encoder/self_attention_mask/mul"
input: "model/bert_encoder/transformer/layer_0/self_attention/query/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_0/self_attention/query/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_0/self_attention/key/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_0/self_attention/key/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_0/self_attention/value/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_0/self_attention/value/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_0/self_attention/attention_output/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_0/self_attention/attention_output/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_0/self_attention_layer_norm/batchnorm/mul/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_0/self_attention_layer_norm/batchnorm/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_0/intermediate/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_0/intermediate/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_0/output/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_0/output/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_0/output_layer_norm/batchnorm/mul/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_0/output_layer_norm/batchnorm/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_1/self_attention/query/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_1/self_attention/query/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_1/self_attention/key/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_1/self_attention/key/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_1/self_attention/value/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_1/self_attention/value/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_1/self_attention/attention_output/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_1/self_attention/attention_output/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_1/self_attention_layer_norm/batchnorm/mul/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_1/self_attention_layer_norm/batchnorm/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_1/intermediate/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_1/intermediate/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_1/output/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_1/output/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_1/output_layer_norm/batchnorm/mul/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_1/output_layer_norm/batchnorm/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_2/self_attention/query/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_2/self_attention/query/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_2/self_attention/key/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_2/self_attention/key/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_2/self_attention/value/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_2/self_attention/value/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_2/self_attention/attention_output/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_2/self_attention/attention_output/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_2/self_attention_layer_norm/batchnorm/mul/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_2/self_attention_layer_norm/batchnorm/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_2/intermediate/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_2/intermediate/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_2/output/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_2/output/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_2/output_layer_norm/batchnorm/mul/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_2/output_layer_norm/batchnorm/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_3/self_attention/query/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_3/self_attention/query/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_3/self_attention/key/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_3/self_attention/key/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_3/self_attention/value/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_3/self_attention/value/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_3/self_attention/attention_output/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_3/self_attention/attention_output/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_3/self_attention_layer_norm/batchnorm/mul/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_3/self_attention_layer_norm/batchnorm/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_3/intermediate/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_3/intermediate/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_3/output/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_3/output/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_3/output_layer_norm/batchnorm/mul/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_3/output_layer_norm/batchnorm/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_4/self_attention/query/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_4/self_attention/query/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_4/self_attention/key/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_4/self_attention/key/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_4/self_attention/value/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_4/self_attention/value/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_4/self_attention/attention_output/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_4/self_attention/attention_output/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_4/self_attention_layer_norm/batchnorm/mul/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_4/self_attention_layer_norm/batchnorm/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_4/intermediate/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_4/intermediate/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_4/output/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_4/output/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_4/output_layer_norm/batchnorm/mul/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_4/output_layer_norm/batchnorm/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_5/self_attention/query/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_5/self_attention/query/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_5/self_attention/key/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_5/self_attention/key/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_5/self_attention/value/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_5/self_attention/value/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_5/self_attention/attention_output/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_5/self_attention/attention_output/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_5/self_attention_layer_norm/batchnorm/mul/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_5/self_attention_layer_norm/batchnorm/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_5/intermediate/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_5/intermediate/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_5/output/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_5/output/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_5/output_layer_norm/batchnorm/mul/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_5/output_layer_norm/batchnorm/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_6/self_attention/query/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_6/self_attention/query/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_6/self_attention/key/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_6/self_attention/key/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_6/self_attention/value/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_6/self_attention/value/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_6/self_attention/attention_output/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_6/self_attention/attention_output/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_6/self_attention_layer_norm/batchnorm/mul/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_6/self_attention_layer_norm/batchnorm/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_6/intermediate/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_6/intermediate/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_6/output/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_6/output/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_6/output_layer_norm/batchnorm/mul/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_6/output_layer_norm/batchnorm/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_7/self_attention/query/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_7/self_attention/query/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_7/self_attention/key/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_7/self_attention/key/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_7/self_attention/value/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_7/self_attention/value/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_7/self_attention/attention_output/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_7/self_attention/attention_output/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_7/self_attention_layer_norm/batchnorm/mul/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_7/self_attention_layer_norm/batchnorm/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_7/intermediate/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_7/intermediate/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_7/output/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_7/output/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_7/output_layer_norm/batchnorm/mul/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_7/output_layer_norm/batchnorm/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_8/self_attention/query/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_8/self_attention/query/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_8/self_attention/key/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_8/self_attention/key/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_8/self_attention/value/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_8/self_attention/value/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_8/self_attention/attention_output/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_8/self_attention/attention_output/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_8/self_attention_layer_norm/batchnorm/mul/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_8/self_attention_layer_norm/batchnorm/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_8/intermediate/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_8/intermediate/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_8/output/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_8/output/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_8/output_layer_norm/batchnorm/mul/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_8/output_layer_norm/batchnorm/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_9/self_attention/query/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_9/self_attention/query/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_9/self_attention/key/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_9/self_attention/key/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_9/self_attention/value/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_9/self_attention/value/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_9/self_attention/attention_output/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_9/self_attention/attention_output/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_9/self_attention_layer_norm/batchnorm/mul/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_9/self_attention_layer_norm/batchnorm/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_9/intermediate/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_9/intermediate/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_9/output/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_9/output/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_9/output_layer_norm/batchnorm/mul/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_9/output_layer_norm/batchnorm/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_10/self_attention/query/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_10/self_attention/query/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_10/self_attention/key/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_10/self_attention/key/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_10/self_attention/value/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_10/self_attention/value/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_10/self_attention/attention_output/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_10/self_attention/attention_output/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_10/self_attention_layer_norm/batchnorm/mul/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_10/self_attention_layer_norm/batchnorm/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_10/intermediate/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_10/intermediate/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_10/output/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_10/output/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_10/output_layer_norm/batchnorm/mul/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_10/output_layer_norm/batchnorm/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_11/self_attention/query/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_11/self_attention/query/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_11/self_attention/key/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_11/self_attention/key/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_11/self_attention/value/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_11/self_attention/value/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_11/self_attention/attention_output/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_11/self_attention/attention_output/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_11/self_attention_layer_norm/batchnorm/mul/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_11/self_attention_layer_norm/batchnorm/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_11/intermediate/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_11/intermediate/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_11/output/einsum/Einsum/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_11/output/add/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_11/output_layer_norm/batchnorm/mul/ReadVariableOp"
input: "model/bert_encoder/transformer/layer_11/output_layer_norm/batchnorm/ReadVariableOp"
attr {
  key: "HiddenAct"
  value {
    s: "gelu_tanh"
  }
}
attr {
  key: "HiddenSize"
  value {
    i: 768
  }
}
attr {
  key: "IntermediateSize"
  value {
    i: 3072
  }
}
attr {
  key: "MaskT"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "NumAttentionHeads"
  value {
    i: 12
  }
}
attr {
  key: "NumWeights"
  value {
    i: 192
  }
}
attr {
  key: "_output_shapes"
  value {
    list {
      shape {
        unknown_rank: true
      }
    }
  }
}
