name: "fused_bert"
op: "Bert"
input: "bert/embeddings/dropout/Identity"
input: "bert/Cast"
input:  "bert/encoder/layer_._0/attention/self/query/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._0/attention/self/query/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._0/attention/self/key/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._0/attention/self/key/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._0/attention/self/value/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._0/attention/self/value/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._0/attention/output/dense/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._0/attention/output/dense/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._0/attention/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input:  "bert/encoder/layer_._0/attention/output/LayerNorm/batchnorm/ReadVariableOp"
input:  "bert/encoder/layer_._0/intermediate/dense/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._0/intermediate/dense/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._0/output/dense/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._0/output/dense/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._0/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input:  "bert/encoder/layer_._0/output/LayerNorm/batchnorm/ReadVariableOp"
input:  "bert/encoder/layer_._1/attention/self/query/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._1/attention/self/query/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._1/attention/self/key/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._1/attention/self/key/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._1/attention/self/value/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._1/attention/self/value/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._1/attention/output/dense/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._1/attention/output/dense/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._1/attention/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input:  "bert/encoder/layer_._1/attention/output/LayerNorm/batchnorm/ReadVariableOp"
input:  "bert/encoder/layer_._1/intermediate/dense/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._1/intermediate/dense/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._1/output/dense/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._1/output/dense/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._1/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input:  "bert/encoder/layer_._1/output/LayerNorm/batchnorm/ReadVariableOp"
input:  "bert/encoder/layer_._2/attention/self/query/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._2/attention/self/query/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._2/attention/self/key/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._2/attention/self/key/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._2/attention/self/value/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._2/attention/self/value/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._2/attention/output/dense/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._2/attention/output/dense/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._2/attention/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input:  "bert/encoder/layer_._2/attention/output/LayerNorm/batchnorm/ReadVariableOp"
input:  "bert/encoder/layer_._2/intermediate/dense/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._2/intermediate/dense/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._2/output/dense/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._2/output/dense/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._2/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input:  "bert/encoder/layer_._2/output/LayerNorm/batchnorm/ReadVariableOp"
input:  "bert/encoder/layer_._3/attention/self/query/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._3/attention/self/query/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._3/attention/self/key/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._3/attention/self/key/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._3/attention/self/value/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._3/attention/self/value/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._3/attention/output/dense/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._3/attention/output/dense/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._3/attention/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input:  "bert/encoder/layer_._3/attention/output/LayerNorm/batchnorm/ReadVariableOp"
input:  "bert/encoder/layer_._3/intermediate/dense/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._3/intermediate/dense/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._3/output/dense/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._3/output/dense/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._3/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input:  "bert/encoder/layer_._3/output/LayerNorm/batchnorm/ReadVariableOp"
input:  "bert/encoder/layer_._4/attention/self/query/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._4/attention/self/query/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._4/attention/self/key/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._4/attention/self/key/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._4/attention/self/value/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._4/attention/self/value/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._4/attention/output/dense/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._4/attention/output/dense/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._4/attention/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input:  "bert/encoder/layer_._4/attention/output/LayerNorm/batchnorm/ReadVariableOp"
input:  "bert/encoder/layer_._4/intermediate/dense/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._4/intermediate/dense/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._4/output/dense/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._4/output/dense/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._4/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input:  "bert/encoder/layer_._4/output/LayerNorm/batchnorm/ReadVariableOp"
input:  "bert/encoder/layer_._5/attention/self/query/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._5/attention/self/query/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._5/attention/self/key/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._5/attention/self/key/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._5/attention/self/value/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._5/attention/self/value/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._5/attention/output/dense/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._5/attention/output/dense/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._5/attention/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input:  "bert/encoder/layer_._5/attention/output/LayerNorm/batchnorm/ReadVariableOp"
input:  "bert/encoder/layer_._5/intermediate/dense/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._5/intermediate/dense/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._5/output/dense/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._5/output/dense/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._5/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input:  "bert/encoder/layer_._5/output/LayerNorm/batchnorm/ReadVariableOp"
input:  "bert/encoder/layer_._6/attention/self/query/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._6/attention/self/query/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._6/attention/self/key/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._6/attention/self/key/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._6/attention/self/value/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._6/attention/self/value/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._6/attention/output/dense/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._6/attention/output/dense/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._6/attention/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input:  "bert/encoder/layer_._6/attention/output/LayerNorm/batchnorm/ReadVariableOp"
input:  "bert/encoder/layer_._6/intermediate/dense/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._6/intermediate/dense/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._6/output/dense/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._6/output/dense/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._6/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input:  "bert/encoder/layer_._6/output/LayerNorm/batchnorm/ReadVariableOp"
input:  "bert/encoder/layer_._7/attention/self/query/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._7/attention/self/query/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._7/attention/self/key/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._7/attention/self/key/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._7/attention/self/value/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._7/attention/self/value/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._7/attention/output/dense/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._7/attention/output/dense/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._7/attention/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input:  "bert/encoder/layer_._7/attention/output/LayerNorm/batchnorm/ReadVariableOp"
input:  "bert/encoder/layer_._7/intermediate/dense/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._7/intermediate/dense/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._7/output/dense/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._7/output/dense/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._7/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input:  "bert/encoder/layer_._7/output/LayerNorm/batchnorm/ReadVariableOp"
input:  "bert/encoder/layer_._8/attention/self/query/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._8/attention/self/query/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._8/attention/self/key/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._8/attention/self/key/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._8/attention/self/value/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._8/attention/self/value/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._8/attention/output/dense/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._8/attention/output/dense/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._8/attention/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input:  "bert/encoder/layer_._8/attention/output/LayerNorm/batchnorm/ReadVariableOp"
input:  "bert/encoder/layer_._8/intermediate/dense/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._8/intermediate/dense/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._8/output/dense/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._8/output/dense/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._8/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input:  "bert/encoder/layer_._8/output/LayerNorm/batchnorm/ReadVariableOp"
input:  "bert/encoder/layer_._9/attention/self/query/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._9/attention/self/query/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._9/attention/self/key/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._9/attention/self/key/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._9/attention/self/value/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._9/attention/self/value/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._9/attention/output/dense/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._9/attention/output/dense/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._9/attention/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input:  "bert/encoder/layer_._9/attention/output/LayerNorm/batchnorm/ReadVariableOp"
input:  "bert/encoder/layer_._9/intermediate/dense/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._9/intermediate/dense/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._9/output/dense/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._9/output/dense/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._9/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input:  "bert/encoder/layer_._9/output/LayerNorm/batchnorm/ReadVariableOp"
input:  "bert/encoder/layer_._10/attention/self/query/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._10/attention/self/query/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._10/attention/self/key/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._10/attention/self/key/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._10/attention/self/value/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._10/attention/self/value/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._10/attention/output/dense/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._10/attention/output/dense/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._10/attention/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input:  "bert/encoder/layer_._10/attention/output/LayerNorm/batchnorm/ReadVariableOp"
input:  "bert/encoder/layer_._10/intermediate/dense/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._10/intermediate/dense/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._10/output/dense/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._10/output/dense/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._10/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input:  "bert/encoder/layer_._10/output/LayerNorm/batchnorm/ReadVariableOp"
input:  "bert/encoder/layer_._11/attention/self/query/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._11/attention/self/query/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._11/attention/self/key/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._11/attention/self/key/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._11/attention/self/value/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._11/attention/self/value/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._11/attention/output/dense/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._11/attention/output/dense/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._11/attention/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input:  "bert/encoder/layer_._11/attention/output/LayerNorm/batchnorm/ReadVariableOp"
input:  "bert/encoder/layer_._11/intermediate/dense/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._11/intermediate/dense/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._11/output/dense/Tensordot/ReadVariableOp"
input:  "bert/encoder/layer_._11/output/dense/BiasAdd/ReadVariableOp"
input:  "bert/encoder/layer_._11/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input:  "bert/encoder/layer_._11/output/LayerNorm/batchnorm/ReadVariableOp"
attr {
  key: "NonQuantizableDataType"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "QuantizableDataType"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "HiddenAct"
  value {
    s: "gelu_tanh"
  }
}
attr {
  key: "HiddenSize"
  value {
    i: 768
  }
}
attr {
  key: "IntermediateSize"
  value {
    i: 3072
  }
}
attr {
  key: "MaskT"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "NumAttentionHeads"
  value {
    i: 12
  }
}
attr {
  key: "NumWeights"
  value {
    i: 192
  }
}
attr {
  key: "_output_shapes"
  value {
    list {
      shape {
        unknown_rank: true
      }
    }
  }
}
