name: "fused_bert"
op: "Bert"
input: "bert/embeddings/dropout/Identity"
input: "bert/Cast"
input: "bert/encoder/layer_._0/attention/self/query/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._0/attention/self/query/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._0/attention/self/key/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._0/attention/self/key/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._0/attention/self/value/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._0/attention/self/value/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._0/attention/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._0/attention/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._0/attention/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._0/attention/output/LayerNorm/batchnorm/ReadVariableOp"
input: "bert/encoder/layer_._0/intermediate/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._0/intermediate/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._0/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._0/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._0/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._0/output/LayerNorm/batchnorm/ReadVariableOp"
input: "bert/encoder/layer_._1/attention/self/query/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._1/attention/self/query/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._1/attention/self/key/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._1/attention/self/key/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._1/attention/self/value/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._1/attention/self/value/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._1/attention/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._1/attention/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._1/attention/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._1/attention/output/LayerNorm/batchnorm/ReadVariableOp"
input: "bert/encoder/layer_._1/intermediate/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._1/intermediate/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._1/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._1/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._1/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._1/output/LayerNorm/batchnorm/ReadVariableOp"
input: "bert/encoder/layer_._2/attention/self/query/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._2/attention/self/query/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._2/attention/self/key/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._2/attention/self/key/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._2/attention/self/value/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._2/attention/self/value/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._2/attention/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._2/attention/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._2/attention/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._2/attention/output/LayerNorm/batchnorm/ReadVariableOp"
input: "bert/encoder/layer_._2/intermediate/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._2/intermediate/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._2/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._2/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._2/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._2/output/LayerNorm/batchnorm/ReadVariableOp"
input: "bert/encoder/layer_._3/attention/self/query/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._3/attention/self/query/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._3/attention/self/key/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._3/attention/self/key/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._3/attention/self/value/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._3/attention/self/value/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._3/attention/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._3/attention/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._3/attention/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._3/attention/output/LayerNorm/batchnorm/ReadVariableOp"
input: "bert/encoder/layer_._3/intermediate/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._3/intermediate/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._3/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._3/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._3/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._3/output/LayerNorm/batchnorm/ReadVariableOp"
input: "bert/encoder/layer_._4/attention/self/query/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._4/attention/self/query/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._4/attention/self/key/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._4/attention/self/key/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._4/attention/self/value/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._4/attention/self/value/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._4/attention/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._4/attention/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._4/attention/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._4/attention/output/LayerNorm/batchnorm/ReadVariableOp"
input: "bert/encoder/layer_._4/intermediate/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._4/intermediate/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._4/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._4/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._4/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._4/output/LayerNorm/batchnorm/ReadVariableOp"
input: "bert/encoder/layer_._5/attention/self/query/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._5/attention/self/query/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._5/attention/self/key/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._5/attention/self/key/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._5/attention/self/value/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._5/attention/self/value/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._5/attention/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._5/attention/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._5/attention/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._5/attention/output/LayerNorm/batchnorm/ReadVariableOp"
input: "bert/encoder/layer_._5/intermediate/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._5/intermediate/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._5/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._5/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._5/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._5/output/LayerNorm/batchnorm/ReadVariableOp"
input: "bert/encoder/layer_._6/attention/self/query/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._6/attention/self/query/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._6/attention/self/key/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._6/attention/self/key/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._6/attention/self/value/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._6/attention/self/value/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._6/attention/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._6/attention/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._6/attention/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._6/attention/output/LayerNorm/batchnorm/ReadVariableOp"
input: "bert/encoder/layer_._6/intermediate/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._6/intermediate/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._6/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._6/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._6/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._6/output/LayerNorm/batchnorm/ReadVariableOp"
input: "bert/encoder/layer_._7/attention/self/query/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._7/attention/self/query/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._7/attention/self/key/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._7/attention/self/key/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._7/attention/self/value/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._7/attention/self/value/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._7/attention/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._7/attention/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._7/attention/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._7/attention/output/LayerNorm/batchnorm/ReadVariableOp"
input: "bert/encoder/layer_._7/intermediate/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._7/intermediate/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._7/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._7/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._7/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._7/output/LayerNorm/batchnorm/ReadVariableOp"
input: "bert/encoder/layer_._8/attention/self/query/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._8/attention/self/query/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._8/attention/self/key/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._8/attention/self/key/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._8/attention/self/value/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._8/attention/self/value/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._8/attention/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._8/attention/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._8/attention/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._8/attention/output/LayerNorm/batchnorm/ReadVariableOp"
input: "bert/encoder/layer_._8/intermediate/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._8/intermediate/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._8/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._8/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._8/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._8/output/LayerNorm/batchnorm/ReadVariableOp"
input: "bert/encoder/layer_._9/attention/self/query/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._9/attention/self/query/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._9/attention/self/key/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._9/attention/self/key/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._9/attention/self/value/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._9/attention/self/value/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._9/attention/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._9/attention/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._9/attention/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._9/attention/output/LayerNorm/batchnorm/ReadVariableOp"
input: "bert/encoder/layer_._9/intermediate/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._9/intermediate/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._9/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._9/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._9/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._9/output/LayerNorm/batchnorm/ReadVariableOp"
input: "bert/encoder/layer_._10/attention/self/query/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._10/attention/self/query/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._10/attention/self/key/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._10/attention/self/key/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._10/attention/self/value/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._10/attention/self/value/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._10/attention/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._10/attention/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._10/attention/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._10/attention/output/LayerNorm/batchnorm/ReadVariableOp"
input: "bert/encoder/layer_._10/intermediate/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._10/intermediate/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._10/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._10/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._10/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._10/output/LayerNorm/batchnorm/ReadVariableOp"
input: "bert/encoder/layer_._11/attention/self/query/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._11/attention/self/query/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._11/attention/self/key/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._11/attention/self/key/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._11/attention/self/value/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._11/attention/self/value/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._11/attention/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._11/attention/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._11/attention/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._11/attention/output/LayerNorm/batchnorm/ReadVariableOp"
input: "bert/encoder/layer_._11/intermediate/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._11/intermediate/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._11/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._11/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._11/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._11/output/LayerNorm/batchnorm/ReadVariableOp"
input: "bert/encoder/layer_._12/attention/self/query/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._12/attention/self/query/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._12/attention/self/key/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._12/attention/self/key/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._12/attention/self/value/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._12/attention/self/value/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._12/attention/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._12/attention/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._12/attention/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._12/attention/output/LayerNorm/batchnorm/ReadVariableOp"
input: "bert/encoder/layer_._12/intermediate/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._12/intermediate/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._12/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._12/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._12/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._12/output/LayerNorm/batchnorm/ReadVariableOp"
input: "bert/encoder/layer_._13/attention/self/query/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._13/attention/self/query/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._13/attention/self/key/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._13/attention/self/key/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._13/attention/self/value/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._13/attention/self/value/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._13/attention/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._13/attention/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._13/attention/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._13/attention/output/LayerNorm/batchnorm/ReadVariableOp"
input: "bert/encoder/layer_._13/intermediate/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._13/intermediate/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._13/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._13/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._13/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._13/output/LayerNorm/batchnorm/ReadVariableOp"
input: "bert/encoder/layer_._14/attention/self/query/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._14/attention/self/query/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._14/attention/self/key/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._14/attention/self/key/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._14/attention/self/value/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._14/attention/self/value/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._14/attention/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._14/attention/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._14/attention/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._14/attention/output/LayerNorm/batchnorm/ReadVariableOp"
input: "bert/encoder/layer_._14/intermediate/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._14/intermediate/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._14/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._14/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._14/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._14/output/LayerNorm/batchnorm/ReadVariableOp"
input: "bert/encoder/layer_._15/attention/self/query/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._15/attention/self/query/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._15/attention/self/key/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._15/attention/self/key/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._15/attention/self/value/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._15/attention/self/value/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._15/attention/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._15/attention/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._15/attention/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._15/attention/output/LayerNorm/batchnorm/ReadVariableOp"
input: "bert/encoder/layer_._15/intermediate/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._15/intermediate/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._15/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._15/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._15/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._15/output/LayerNorm/batchnorm/ReadVariableOp"
input: "bert/encoder/layer_._16/attention/self/query/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._16/attention/self/query/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._16/attention/self/key/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._16/attention/self/key/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._16/attention/self/value/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._16/attention/self/value/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._16/attention/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._16/attention/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._16/attention/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._16/attention/output/LayerNorm/batchnorm/ReadVariableOp"
input: "bert/encoder/layer_._16/intermediate/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._16/intermediate/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._16/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._16/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._16/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._16/output/LayerNorm/batchnorm/ReadVariableOp"
input: "bert/encoder/layer_._17/attention/self/query/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._17/attention/self/query/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._17/attention/self/key/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._17/attention/self/key/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._17/attention/self/value/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._17/attention/self/value/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._17/attention/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._17/attention/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._17/attention/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._17/attention/output/LayerNorm/batchnorm/ReadVariableOp"
input: "bert/encoder/layer_._17/intermediate/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._17/intermediate/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._17/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._17/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._17/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._17/output/LayerNorm/batchnorm/ReadVariableOp"
input: "bert/encoder/layer_._18/attention/self/query/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._18/attention/self/query/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._18/attention/self/key/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._18/attention/self/key/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._18/attention/self/value/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._18/attention/self/value/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._18/attention/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._18/attention/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._18/attention/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._18/attention/output/LayerNorm/batchnorm/ReadVariableOp"
input: "bert/encoder/layer_._18/intermediate/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._18/intermediate/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._18/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._18/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._18/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._18/output/LayerNorm/batchnorm/ReadVariableOp"
input: "bert/encoder/layer_._19/attention/self/query/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._19/attention/self/query/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._19/attention/self/key/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._19/attention/self/key/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._19/attention/self/value/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._19/attention/self/value/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._19/attention/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._19/attention/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._19/attention/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._19/attention/output/LayerNorm/batchnorm/ReadVariableOp"
input: "bert/encoder/layer_._19/intermediate/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._19/intermediate/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._19/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._19/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._19/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._19/output/LayerNorm/batchnorm/ReadVariableOp"
input: "bert/encoder/layer_._20/attention/self/query/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._20/attention/self/query/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._20/attention/self/key/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._20/attention/self/key/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._20/attention/self/value/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._20/attention/self/value/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._20/attention/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._20/attention/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._20/attention/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._20/attention/output/LayerNorm/batchnorm/ReadVariableOp"
input: "bert/encoder/layer_._20/intermediate/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._20/intermediate/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._20/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._20/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._20/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._20/output/LayerNorm/batchnorm/ReadVariableOp"
input: "bert/encoder/layer_._21/attention/self/query/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._21/attention/self/query/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._21/attention/self/key/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._21/attention/self/key/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._21/attention/self/value/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._21/attention/self/value/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._21/attention/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._21/attention/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._21/attention/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._21/attention/output/LayerNorm/batchnorm/ReadVariableOp"
input: "bert/encoder/layer_._21/intermediate/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._21/intermediate/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._21/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._21/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._21/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._21/output/LayerNorm/batchnorm/ReadVariableOp"
input: "bert/encoder/layer_._22/attention/self/query/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._22/attention/self/query/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._22/attention/self/key/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._22/attention/self/key/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._22/attention/self/value/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._22/attention/self/value/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._22/attention/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._22/attention/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._22/attention/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._22/attention/output/LayerNorm/batchnorm/ReadVariableOp"
input: "bert/encoder/layer_._22/intermediate/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._22/intermediate/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._22/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._22/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._22/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._22/output/LayerNorm/batchnorm/ReadVariableOp"
input: "bert/encoder/layer_._23/attention/self/query/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._23/attention/self/query/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._23/attention/self/key/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._23/attention/self/key/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._23/attention/self/value/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._23/attention/self/value/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._23/attention/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._23/attention/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._23/attention/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._23/attention/output/LayerNorm/batchnorm/ReadVariableOp"
input: "bert/encoder/layer_._23/intermediate/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._23/intermediate/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._23/output/dense/Tensordot/ReadVariableOp"
input: "bert/encoder/layer_._23/output/dense/BiasAdd/ReadVariableOp"
input: "bert/encoder/layer_._23/output/LayerNorm/batchnorm/mul/ReadVariableOp"
input: "bert/encoder/layer_._23/output/LayerNorm/batchnorm/ReadVariableOp"
attr {
  key: "HiddenAct"
  value {
    s: "gelu_tanh"
  }
}
attr {
  key: "HiddenSize"
  value {
    i: 1024
  }
}
attr { 
  key: "IntermediateSize"
  value {
    i: 4096
  }
}
attr {
   key: "MaskT"
   value {
     type: DT_FLOAT
   }
}
attr {
  key: "NumAttentionHeads"
  value {
    i: 16
  }
}
attr {
  key: "NumWeights"
  value {
    i: 384
  }
}
attr {
  key: "_output_shapes"
  value {
    list {
      shape {
        unknown_rank: true
      }
    }
  }
}
